apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}-secret
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
   #TODO not upgrade safe
    root-password: {{ randAlphaNum 32 | b64enc | quote }}
    mysql-user: {{ "s3-bench" | b64enc | quote}}
    mysql-password: {{ randAlphaNum 32 | b64enc | quote }}
    mysql-database: {{ "s3-bench" | b64enc | quote}}
